using System;
using System.Collections.Generic;
using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
#endif

/// <summary>
/// nextWaypointsから有向閉路を検出し、TrafficDeadlockZoneを生成します。
/// Waypoint名には依存しません。
///
/// まずmaximumCycleLength以下の単純閉路を探索し、1件も検出できない場合は
/// 強連結成分（相互に到達可能なWaypoint群）をZoneとして生成します。
/// </summary>
public class DeadlockZoneAutoSetup : MonoBehaviour
{
    [Header("References")]
    public Transform waypointRoot;
    public Transform generatedZoneRoot;
    public MergeTrafficCoordinator coordinator;

    [Header("Cycle Detection")]
    [Min(2)]
    public int minimumCycleLength = 2;

    [Min(3)]
    public int maximumCycleLength = 24;

    [Min(1)]
    public int maximumGeneratedZones = 200;

    [Tooltip("同じWaypoint集合の閉路は1つへ統合します。")]
    public bool mergeEquivalentCycles = true;

    [Tooltip("大きい閉路が小さい閉路を完全に含む場合、大きい側を省略します。")]
    public bool removeSupersetCycles = true;

    [Tooltip("短い閉路を検出できなかった場合、強連結成分をZoneとして生成します。")]
    public bool useStronglyConnectedFallback = true;

    [Header("Generated Zone")]
    [Min(1)]
    public int reservedEmptyWaypoints = 1;

    public bool replacePreviouslyGenerated = true;
    public string generatedNamePrefix = "AutoDeadlockZone_";

    [Header("Last Result")]
    [TextArea(6, 30)]
    public string lastResult;

    [ContextMenu("Generate Deadlock Zones")]
    public void GenerateZones()
    {
        Waypoint[] waypoints = CollectWaypoints();
        Transform root = generatedZoneRoot != null ? generatedZoneRoot : transform;

        if (replacePreviouslyGenerated)
            RemoveGeneratedZones(root);

        List<List<Waypoint>> zones = FindSimpleCycles(waypoints);
        string mode = "SimpleCycles";

        if (removeSupersetCycles)
            zones = RemoveSupersets(zones);

        if (zones.Count == 0 && useStronglyConnectedFallback)
        {
            zones = FindStronglyConnectedComponents(waypoints);
            mode = "StronglyConnectedFallback";
        }

        if (zones.Count > maximumGeneratedZones)
            zones.RemoveRange(maximumGeneratedZones, zones.Count - maximumGeneratedZones);

        int index = 1;
        foreach (List<Waypoint> members in zones)
        {
            if (members == null || members.Count < 2)
                continue;

            GameObject created = new GameObject(
                generatedNamePrefix + index.ToString("00"));
            created.transform.SetParent(root, false);
            created.transform.position = members[0].transform.position;

            AutoGeneratedDeadlockZone marker =
                created.AddComponent<AutoGeneratedDeadlockZone>();
            marker.memberCount = members.Count;

            TrafficDeadlockZone zone =
                created.AddComponent<TrafficDeadlockZone>();
            zone.zoneId = created.name;
            zone.memberWaypoints.AddRange(members);
            zone.reservedEmptyWaypoints = Mathf.Max(1, reservedEmptyWaypoints);
            index++;
        }

        MergeTrafficCoordinator active = ResolveCoordinator();
        if (active != null)
        {
            active.CollectDeadlockZones();
            active.RebuildLookup();
        }

        int generated = index - 1;
        lastResult =
            $"Generated={generated}, Mode={mode}, Waypoints={waypoints.Length}, " +
            $"Min={minimumCycleLength}, Max={maximumCycleLength}";

        if (generated == 0)
            Debug.LogWarning(lastResult + "。nextWaypointsに有向閉路がありません。", this);
        else
            Debug.Log(lastResult, this);
    }

    private List<List<Waypoint>> FindSimpleCycles(Waypoint[] waypoints)
    {
        List<List<Waypoint>> result = new List<List<Waypoint>>();
        HashSet<string> keys = new HashSet<string>();

        foreach (Waypoint start in waypoints)
        {
            if (start == null || result.Count >= maximumGeneratedZones)
                continue;

            List<Waypoint> path = new List<Waypoint>();
            HashSet<Waypoint> inPath = new HashSet<Waypoint>();
            SearchCycle(start, start, path, inPath, result, keys);
        }

        return result;
    }

    private void SearchCycle(
        Waypoint start,
        Waypoint current,
        List<Waypoint> path,
        HashSet<Waypoint> inPath,
        List<List<Waypoint>> result,
        HashSet<string> keys)
    {
        if (current == null ||
            path.Count >= maximumCycleLength ||
            result.Count >= maximumGeneratedZones)
            return;

        path.Add(current);
        inPath.Add(current);

        if (current.nextWaypoints != null)
        {
            foreach (Waypoint next in current.nextWaypoints)
            {
                if (next == null)
                    continue;

                if (next == start)
                {
                    if (path.Count >= minimumCycleLength)
                    {
                        List<Waypoint> cycle = new List<Waypoint>(path);
                        string key = BuildCycleKey(cycle);
                        if (keys.Add(key))
                            result.Add(cycle);
                    }
                    continue;
                }

                if (!inPath.Contains(next))
                    SearchCycle(start, next, path, inPath, result, keys);

                if (result.Count >= maximumGeneratedZones)
                    break;
            }
        }

        inPath.Remove(current);
        path.RemoveAt(path.Count - 1);
    }

    private string BuildCycleKey(List<Waypoint> cycle)
    {
        List<int> ids = new List<int>();
        foreach (Waypoint waypoint in cycle)
            ids.Add(waypoint != null ? waypoint.GetInstanceID() : 0);

        if (mergeEquivalentCycles)
            ids.Sort();

        return string.Join("|", ids);
    }

    private List<List<Waypoint>> FindStronglyConnectedComponents(Waypoint[] waypoints)
    {
        List<List<Waypoint>> result = new List<List<Waypoint>>();
        Dictionary<Waypoint, int> indexByNode = new Dictionary<Waypoint, int>();
        Dictionary<Waypoint, int> lowLink = new Dictionary<Waypoint, int>();
        Stack<Waypoint> stack = new Stack<Waypoint>();
        HashSet<Waypoint> onStack = new HashSet<Waypoint>();
        int index = 0;

        foreach (Waypoint waypoint in waypoints)
        {
            if (waypoint != null && !indexByNode.ContainsKey(waypoint))
                StrongConnect(waypoint, ref index, indexByNode, lowLink, stack, onStack, result);
        }

        return result;
    }

    private void StrongConnect(
        Waypoint node,
        ref int index,
        Dictionary<Waypoint, int> indexByNode,
        Dictionary<Waypoint, int> lowLink,
        Stack<Waypoint> stack,
        HashSet<Waypoint> onStack,
        List<List<Waypoint>> result)
    {
        indexByNode[node] = index;
        lowLink[node] = index;
        index++;
        stack.Push(node);
        onStack.Add(node);

        if (node.nextWaypoints != null)
        {
            foreach (Waypoint next in node.nextWaypoints)
            {
                if (next == null)
                    continue;

                if (!indexByNode.ContainsKey(next))
                {
                    StrongConnect(next, ref index, indexByNode, lowLink, stack, onStack, result);
                    lowLink[node] = Mathf.Min(lowLink[node], lowLink[next]);
                }
                else if (onStack.Contains(next))
                {
                    lowLink[node] = Mathf.Min(lowLink[node], indexByNode[next]);
                }
            }
        }

        if (lowLink[node] != indexByNode[node])
            return;

        List<Waypoint> component = new List<Waypoint>();
        Waypoint popped;
        do
        {
            popped = stack.Pop();
            onStack.Remove(popped);
            component.Add(popped);
        }
        while (popped != node);

        bool selfLoop =
            component.Count == 1 &&
            component[0].nextWaypoints != null &&
            component[0].nextWaypoints.Contains(component[0]);

        if (component.Count >= 2 || selfLoop)
            result.Add(component);
    }

    private static List<List<Waypoint>> RemoveSupersets(List<List<Waypoint>> cycles)
    {
        cycles.Sort((a, b) => a.Count.CompareTo(b.Count));
        List<List<Waypoint>> kept = new List<List<Waypoint>>();

        foreach (List<Waypoint> candidate in cycles)
        {
            HashSet<Waypoint> candidateSet = new HashSet<Waypoint>(candidate);
            bool containsExisting = false;

            foreach (List<Waypoint> existing in kept)
            {
                if (candidateSet.IsSupersetOf(existing))
                {
                    containsExisting = true;
                    break;
                }
            }

            if (!containsExisting)
                kept.Add(candidate);
        }

        return kept;
    }

    private Waypoint[] CollectWaypoints()
    {
        if (waypointRoot != null)
            return waypointRoot.GetComponentsInChildren<Waypoint>(true);

#if UNITY_2023_1_OR_NEWER
        return FindObjectsByType<Waypoint>(
            FindObjectsInactive.Include,
            FindObjectsSortMode.None);
#else
        return FindObjectsOfType<Waypoint>(true);
#endif
    }

    private MergeTrafficCoordinator ResolveCoordinator()
    {
        if (coordinator != null)
            return coordinator;

#if UNITY_2023_1_OR_NEWER
        coordinator = FindFirstObjectByType<MergeTrafficCoordinator>();
#else
        coordinator = FindObjectOfType<MergeTrafficCoordinator>();
#endif
        return coordinator;
    }

    private static void RemoveGeneratedZones(Transform root)
    {
        if (root == null)
            return;

        AutoGeneratedDeadlockZone[] generated =
            root.GetComponentsInChildren<AutoGeneratedDeadlockZone>(true);

        foreach (AutoGeneratedDeadlockZone marker in generated)
        {
            if (marker == null)
                continue;

#if UNITY_EDITOR
            if (!Application.isPlaying)
            {
                Undo.DestroyObjectImmediate(marker.gameObject);
                continue;
            }
#endif
            Destroy(marker.gameObject);
        }
    }
}

public class AutoGeneratedDeadlockZone : MonoBehaviour
{
    public int memberCount;
}